/* Auto-generated by genmsg_cpp for file /home/malcom/src/ros/capygroovy/msg/Ticks.msg */
#ifndef CAPYGROOVY_MESSAGE_TICKS_H
#define CAPYGROOVY_MESSAGE_TICKS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace capygroovy
{
template <class ContainerAllocator>
struct Ticks_ {
  typedef Ticks_<ContainerAllocator> Type;

  Ticks_()
  : header()
  , leftTick(0)
  , rightTick(0)
  {
  }

  Ticks_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , leftTick(0)
  , rightTick(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _leftTick_type;
  int32_t leftTick;

  typedef int32_t _rightTick_type;
  int32_t rightTick;


  typedef boost::shared_ptr< ::capygroovy::Ticks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capygroovy::Ticks_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Ticks
typedef  ::capygroovy::Ticks_<std::allocator<void> > Ticks;

typedef boost::shared_ptr< ::capygroovy::Ticks> TicksPtr;
typedef boost::shared_ptr< ::capygroovy::Ticks const> TicksConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::capygroovy::Ticks_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::capygroovy::Ticks_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace capygroovy

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::capygroovy::Ticks_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::capygroovy::Ticks_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::capygroovy::Ticks_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9e343431b3b11d8350b35ecbcfc68da9";
  }

  static const char* value(const  ::capygroovy::Ticks_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9e343431b3b11d83ULL;
  static const uint64_t static_value2 = 0x50b35ecbcfc68da9ULL;
};

template<class ContainerAllocator>
struct DataType< ::capygroovy::Ticks_<ContainerAllocator> > {
  static const char* value() 
  {
    return "capygroovy/Ticks";
  }

  static const char* value(const  ::capygroovy::Ticks_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::capygroovy::Ticks_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 leftTick\n\
int32 rightTick\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::capygroovy::Ticks_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::capygroovy::Ticks_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::capygroovy::Ticks_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::capygroovy::Ticks_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.leftTick);
    stream.next(m.rightTick);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Ticks_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capygroovy::Ticks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::capygroovy::Ticks_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "leftTick: ";
    Printer<int32_t>::stream(s, indent + "  ", v.leftTick);
    s << indent << "rightTick: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rightTick);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CAPYGROOVY_MESSAGE_TICKS_H

